version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bs-next-app
    ports:
      - "5017:3000"
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: bs-nginx
    ports:
      - "80:80"
    depends_on:
      - nextjs
    restart: always
